substitutions:
  _REGION: "asia-southeast1"
  _REPO: "app-images"
  _SERVICE: "learneyjourney-api"
  _IMAGE: "asia-southeast1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}"

steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE}:${SHORT_SHA}", "."]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE}:${SHORT_SHA}"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - "${_SERVICE}"
      - "--image=${_IMAGE}:${SHORT_SHA}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--cpu=1"
      - "--memory=512Mi"
      - "--min-instances=0"
      - "--max-instances=5"
      # DB connection (uncomment if using Cloud SQL)
      - "--add-cloudsql-instances=p-ying-api:asia-southeast1:learneyjourney-dev"
      # Secrets & env
      - "--set-secrets=DB_PASSWORD=projects/$PROJECT_ID/secrets/DB_PASSWORD:latest"
      - "--set-env-vars=SPRING_PROFILES_ACTIVE=prod"

images:
  - "${_IMAGE}:${SHORT_SHA}"
