spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: appuser   # e.g. postgres
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 60000
      connection-timeout: 20000
      max-lifetime: 1800000
  mail:
    host: smtp.hostinger.com
    port: 465
    username: no-reply@learneyjourney.com
    password: ${SPRING_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
logging:
  level:
    root: info
stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  publish-key: ${STRIPE_PUBLISHABLE_KEY}
  success-url: "https://learneyjourney.com/payment/success"
  cancel-url: "https://learneyjourney.com/payment/cancel"
  webhook-secret: ${STRIPE_WEBHOOK_SECRET_DEV}
  apiBase: "https://api.stripe.com"
  identity:
    return-url: http://localhost:5173/tutor/verification-return
  connect:
    refresh-url: http://localhost:5173/tutor/connect/refresh
    return-url: http://localhost:5173/tutor/connect/return
gcs:
  bucket: learney-media-dev
app:
  baseUrl: "https://learney-frontend-dev-24285490035.asia-southeast1.run.app"
  backendUrl: "https://learney-journey-24285490035.asia-southeast1.run.app"
  allow-origins: "https://learneyjourney.com,https://www.learneyjourney.com,http://localhost:5173, https://learney-frontend-dev-24285490035.asia-southeast1.run.app"
  require-basic-auth: true
  image:
    default-provider: freepik
    unsplash:
      access-key: kK5PW1BVoXwB88PkzXZtt0o70GxqKO-fMICy36fsBxI
    freepik:
      api-key: FPSXe4355aa4943d843496c3b3a1acb6456a
    download:
      connect-timeout-ms: 8000
      read-timeout-ms: 15000
      max-image-bytes: 8000000
      allowed-hosts:
        - images.unsplash.com
        - plus.unsplash.com
        - img.freepik.com
        - image.freepik.com
        - ftp.freepik.com
        - cdni.freepik.com
        - cdn-icons-png.freepik.com
        - cdn-icons-svg.freepik.com
openai:
  base-url: https://api.openai.com
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o
agora:
  app-id: ${AGORA_APP_ID}
  app-certificate: ${AGORA_APP_CERTIFICATE}
  expire-seconds: 3600